### ISSUE TITLE
为什么要拿我的代码改个名又发一遍

### ISSUE THREAD

**Issue by yeyt97** [Darrenpig/Airlink#9]

**Comment by Darrenpig** [comment]
# emmm, 做实验用的，fork了一下，
## 1.想做一下研究更新，没玩过Github。。。抱歉，你在意的话我会删，
## 2.想要更新一下Readme,小白真的不知道release版本才是下载的意思。。。
## 3.研究了一下，想把学学项目的思路。。。Fork仓库是有引用源的

# 一句话，你说删我就删Release版本，并且不发Pull了
